
main:
  - name: Home
    url: '#lab'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: People
    url: '#people'
    weight: 30
  - name: Posts
    url: '#posts'
    weight: 40
  - name: Publications
    url: '#featured'
    weight: 50
